In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [3]:

data = pd.read_csv('/home/killua/Desktop/files/ml/data/Student_Performance.csv')
df = pd.DataFrame(data)
df = df.drop_duplicates()
df.info()

scalerST = StandardScaler()
scalerMM = MinMaxScaler()

<class 'pandas.core.frame.DataFrame'>
Index: 15000 entries, 0 to 14999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             15000 non-null  int64
 1   age                    15000 non-null  int64
 2   gender                 15000 non-null  object
 3   school_type            15000 non-null  object
 4   parent_education       15000 non-null  object
 5   study_hours            15000 non-null  float64
 6   attendance_percentage  15000 non-null  float64
 7   internet_access        15000 non-null  object
 8   travel_time            15000 non-null  object
 9   extra_activities       15000 non-null  object
 10  study_method           15000 non-null  object
 11  math_score             15000 non-null  float64
 12  science_score          15000 non-null  float64
 13  english_score          15000 non-null  float64
 14  overall_score          15000 non-null  float64
 15  final_grade            15000 non-null  object
dtypes: float64(6), int64(2), object(8)
memory usage: 1.9+ MB

In [11]:

print("Gender : ", df['gender'].unique())
print("Age : ", df['age'].unique())
print("School : ", df['school_type'].unique())
print("Parents Education : ", df['parent_education'].unique())
print("Internet Access : ", df['internet_access'].unique())
print("Travel Time : ", df['travel_time'].unique())
print("Activites : ", df['extra_activities'].unique())
print("Study Method : ", df['study_method'].unique())
print("Final Grades : ", df['final_grade'].unique())

Gender :  ['male' 'female' 'other']
Age :  [14 18 17 16 19 15]
School :  ['public' 'private']
Parents Education :  ['post graduate' 'graduate' 'high school' 'no formal' 'diploma' 'phd']
Internet Access :  ['yes' 'no']
Travel Time :  ['<15 min' '>60 min' '15-30 min' '30-60 min']
Activites :  ['yes' 'no']
Study Method :  ['notes' 'textbook' 'group study' 'coaching' 'mixed' 'online videos']
Final Grades :  ['e' 'd' 'b' 'f' 'c' 'a']

In [4]:
# #Gender Mapping/Encoding
# gender_map = {
#     'male': 0,
#     'female': 1,
#     'other': 2
# }
# df['gender'] = df['gender'].map(gender_map)
df = pd.get_dummies(df, columns=['gender','study_method'])

#Encoding Target FInal Grade (Ordinal)
grade_enc = {
    'f' : 0,
    'e' : 1,
    'd' : 2,
    'c' : 3,
    'b' : 4,
    'a' : 5,
}
df['final_grade'] = df['final_grade'].map(grade_enc)


#School Type Mapping
school_type_map = {
    'public' : 0,
    'private' : 1
}
df['school_type'] = df['school_type'].map(school_type_map)


#Parents Education Encoding (Ordinal)
parents_edu_enc = {
    'no formal' : 0,
    'high school' : 1,
    'diploma' : 2,
    'graduate' : 3,
    'post graduate' : 4,
    'phd' : 5
}
df['parent_education'] = df['parent_education'].map(parents_edu_enc)


#Internet access encoding
internet_acc = {
    'yes': 1,
    'no' : 0
}
df['internet_access'] = df['internet_access'].map(internet_acc)


#Travel Time Encoding (Ordinal)
travel_time_enc = {
    '<15 min' : 0,
    '15-30 min' : 1,
    '30-60 min' : 2,
    '>60 min' : 3
}
df['travel_time'] = df['travel_time'].map(travel_time_enc)

#Extra Activities Enc
extra_act_enc = {
    'yes' : 1,
    'no' : 0
}
df['extra_activities'] = df['extra_activities'].map(extra_act_enc)

# df = pd.get_dummies(df, columns=['study_method'])
df.drop(columns=['student_id','math_score','science_score','english_score','overall_score'], inplace=True)

#Scaling stduy_hours and attendance_percentage

# df['study_hours'] = scaler.fit_transform(df[['study_hours']])
# df['attendance_percentage'] = scaler.fit_transform(df[['attendance_percentage']])
# df_scaled = scalerMM.fit_transform(df[['study_hours','attendance_percentage']])
# df[['study_hours','attendance_percentage']] = df_scaled


df.head(10)

,age,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,final_grade,gender_female,gender_male,gender_other,study_method_coaching,study_method_group study,study_method_mixed,study_method_notes,study_method_online videos,study_method_textbook
0,14,0,4,3.1,84.3,1,0,1,1,False,True,False,False,False,False,True,False,False
1,18,0,3,3.7,87.8,1,3,0,2,True,False,False,False,False,False,False,False,True
2,17,1,4,7.9,65.5,0,0,0,4,True,False,False,False,False,False,True,False,False
3,16,0,1,1.1,58.1,0,1,0,1,False,False,True,False,False,False,True,False,False
4,16,0,1,1.3,61.0,1,2,1,0,True,False,False,False,True,False,False,False,False
5,19,0,0,3.8,69.6,1,3,1,2,False,True,False,True,False,False,False,False,False
6,14,1,4,1.8,81.6,1,2,0,0,True,False,False,False,False,False,False,False,True
7,18,1,4,5.6,59.4,1,3,1,2,True,False,False,False,True,False,False,False,False
8,15,1,1,3.2,89.6,1,1,1,2,False,False,True,False,False,True,False,False,False
9,14,0,2,6.8,62.4,1,3,0,2,True,False,False,False,False,True,False,False,False

In [5]:
y = df['final_grade']
X = df.drop(columns=['final_grade'])

scale_cols = ['study_hours', 'attendance_percentage']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

X_train = X_train.copy()
X_test = X_test.copy()

X_train[scale_cols] = scalerMM.fit_transform(X_train[scale_cols])
X_test[scale_cols] = scalerMM.transform(X_test[scale_cols])

In [6]:
X_train.describe()

,age,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities
count,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,16.480583,0.503083,2.494667,0.500850,0.499436,0.851750,1.512833,0.498667
std,1.706565,0.500011,1.689983,0.289698,0.287456,0.355362,1.108349,0.500019
min,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,15.000000,0.000000,1.000000,0.253333,0.252000,1.000000,1.000000,0.000000
50%,16.000000,1.000000,2.000000,0.506667,0.500000,1.000000,2.000000,0.000000
75%,18.000000,1.000000,4.000000,0.746667,0.746000,1.000000,2.000000,1.000000
max,19.000000,1.000000,5.000000,1.000000,1.000000,1.000000,3.000000,1.000000